changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: ⚠️ BREAKING CHANGES
      labels:
        - breaking-change
    - title: 🎉 New Features
      labels:
        - feature
    - title: 🔧 Improvements
      labels:
        - enhancement
    - title: ✅ Bug Fixes
      labels:
        - bug
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
