name: Auto-merge

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    if: >
      github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Auto-merge PR with squash and title
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;

            const pr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: prNumber,
            });

            const isClean = pr.data.mergeable_state === "clean";

            if (isClean) {
              await github.rest.pulls.merge({
                owner,
                repo,
                pull_number: prNumber,
                merge_method: "squash",
                commit_title: pr.data.title,
              });
              console.log(`Squash-merged PR #${prNumber} with title: "${pr.data.title}"`);
            } else {
              console.log(`PR #${prNumber} not mergeable`);
            }
