name: PR Title Checker

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write

jobs:
  check-conventional-title:
    if: github.repository == 'baptistegh/terraform-provider-lakekeeper'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Validate PR title and apply labels
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: "baptistegh/terraform-provider-lakekeeper"
        run: ./.github/pull-request-triage.sh
